urls.py
from django.urls import path
from . import views

app_name = 'cart'

urlpatterns = [
    path('', views.cart_detail, name='cart-detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart-add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart-remove'),
]

models.py
from django.db import models

# Create your models here.

forms.py
from django import forms

PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]

class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
            choices=PRODUCT_QUANTITY_CHOICES,
            coerce=int)
    update = forms.BooleanField(required=False,
            initial=False,
            widget=forms.HiddenInput)

views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from central_supplies.models import Product
from .cart import Cart
from .forms import CartAddProductForm
from django.contrib import messages

# Create your views here.
@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    form = CartAddProductForm(request.POST)
    if form.is_valid():
        cd = form.cleaned_data
        if product.stock < cd['quantity']:
            messages.error(request, f'{product} not added to cart. \
                    Quantity requested {cd["quantity"]} is more than the stock available \
                    {product.stock}.')
        else:
            cart.add(product=product,
                     quantity=cd['quantity'],
                     update_quantity=cd['update'])
    return redirect('cart:cart-detail')

def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart-detail')

def cart_detail(request):
    cart = Cart(request)
    for item in cart:
        item['update_quantity_form'] = CartAddProductForm(
                initial={'quantity': item['quantity'],
                    'update': True})
    return render(request, 'cart/detail.html', {'title': 'Your Shopping Cart', 'cart': cart})

templates/cart/base.html
{% extends 'cm_portal/base.html' %}

templates/cart/detail.html
{% extends 'cart/base.html' %}
{% load static %}

{% block title %}
    Central Supplies | {{ title }}
{% endblock %}

{% block header %}
  {% include 'central_supplies/includes/header.html' %}
{% endblock %}

{% block content %}
  <div class="row p-2"><div class="col-lg-9">
  <h2>{{ title }}</h2>
  <div class="table-responsive-sm"><table class="table table-hover">
    <thead>
      <tr class="table-primary">
        <th scope="row">Image</th>
        <th scope="col">Product</th>
        <th scope="col">Quantity</th>
        <th scope="col">Remove</th>
        <th scope="col">Unit price</th>
        <th scope="col">Price</th>        
      </tr>
    </thead>
    <tbody>
    {% for item in cart %}
      {% with product=item.product %}
      <tr>
        <td>
          <a href="{{ product.get_absolute_url }}">
            <img src="{% if product.image %}{{ product.image.url }}
            {% else %}{% static "img/no_image.jpeg" %}{% endif %}" class="img-thumbnail" alt="Product image">
          </a>
        </td>
        <td>{{ product.name }}</td>
        <td>
          <form action="{% url 'cart:cart-add' product.id %}" method="post" >
            {{ item.update_quantity_form.quantity }}
            {{ item.update_quantity_form.update }}
            {% csrf_token %}
            <input type="submit" value="Update" />
          </form>
        </td>
        <td><a href="{% url "cart:cart-remove" product.id %}">Remove</a></td>
        <td class="num">${{ item.price }}</td>
        <td class="num">${{ item.total_price }}</td>
      </tr>
      {% endwith %}
    {% endfor %}
      <tr class="table-primary">
        <td>Total</td>
        <td colspan="4"></td>
        <td class="num">${{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table></div>
  <p class="text-right">
    <a href="{% url 'central_supplies:product-list' %}" class="btn btn-primary">Continue shopping</a>    
    <a href="{% url 'orders:order-create' %}" class="btn btn-primary">Checkout</a>
  </p>
  
  </div>
{% include "central_supplies/includes/sidebar.html" %}  
  </div>
{% endblock %}

templates/cart/includes/cart.html
<h3><i class="fas fa-shopping-cart"></i> Shopping Cart</h3>
{% with total_items=cart|length %}
  <div class="text-center">{% if cart|length > 0 %}
    You cart:
    <a href="{% url 'cart:cart-detail' %}">
    {{ total_items }} item{{ total_items|pluralize }}
    ${{ cart.get_total_price }}
    </a>    
  {% else %}
    Your cart is empty.
  {% endif %}</div>
{% endwith %}
<hr>